#!/usr/bin/env bash
for var in "$@"
do 
    if [[ -e "$var" ]]
    then
      "/mnt/c/Program Files (x86)/Google/Chrome/Application/chrome.exe" "$(wslpath -w $(pwd)/$var)" 2>&1 >/dev/null &
    else 
      "/mnt/c/Program Files (x86)/Google/Chrome/Application/chrome.exe" "$var" 2>&1 >/dev/null & 
    fi
done
