" Packages?
packadd! matchit

" defaults
source $VIMRUNTIME/defaults.vim
set mouse&

" Regular vim functionaliy
set nu rnu
set scrolloff=3
set colorcolumn=80
set cursorline
set ignorecase
set hlsearch
set showmatch
set matchtime=1
set shiftwidth=4
set softtabstop=4
set expandtab
set laststatus=2
set statusline=%<%f%h%m%r\ %{FugitiveStatusline()}%=%b\ 0x%B\ \ %l,%c%V\ %P
set hidden
" Colors and highlighting
set termguicolors
let g:codedark_modern=1
let g:codedark_italics=0
let g:codedark_transparent=1
colo codedark

" Set netrw home to the home folder rather than the .vim folder
let g:netrw_home=$HOME

"" As per 
"" https://www.youtube.com/watch?v=XA2WjJbmmoM&list=PL8tzorAO7s0jy7DQ3Q0FwF3BnXGQnDirs
"" Enables fuzzy finding of subdirectories???
"" The appended number, <N>, in **<N> determines the search depth
set path+=**3

" Use CTRL-L to clear the highlighting of 'hlsearch' (off by default) and call
" :diffupdate.
if maparg('<C-L>', 'n') ==# ''
  nnoremap <silent> <C-L> :nohlsearch<C-R>=has('diff')?'<Bar>diffupdate':''<CR><CR><C-L>
endif
